### ISSUE TITLE
Update home page content

### ISSUE THREAD

**Issue by stevepiercy** [plone/6.demo.plone.org#3]
The content should be somewhat similar to the other demos:

- https://6-classic.demo.plone.org/
- https://demo.plone.org/

1. Add links to all demo sites.
2. Replace content under "Find out more about Plone" with that from the other demos' "Want to know more?"  section: 
  - [The features of Plone](https://plone.com/features.html)
  - [Plone-Documentation](https://docs.plone.org/)
  - [Plone-Training](https://training.plone.org/)
  - [Forum](https://community.plone.org/)
  - [Add-ons for Plone](https://github.com/collective/awesome-plone#contents)
3. Under "Demo" move login information above the versions info, and insert a new heading "Technical Details".

**Comment by stevepiercy** [comment]
Notes:

- Update only the [Slate section](https://github.com/plone/plone.volto/blob/main/src/plone/volto/default_homepage/demo.py#L348-L639).
- Navigate to https://6.demo.plone.org/, login as `admin/admin`, edit content to that which is desired, save, then open up the browser Inspector tool, Network > XHR > ++api++/ to view the response that may be copy-pasted into the file to be updated.

**Comment by Rudd-O** [comment]
Unrelated, so please do not let this distract the work happening here:

It would be great if we could "Add a site" with an option to have a full demo site, in addition to the existing "Add classic" and "Add Volto" options.

**Comment by stevepiercy** [comment]
> Unrelated, so please do not let this distract the work happening here:
> 
> It would be great if we could "Add a site" with an option to have a full demo site, in addition to the existing "Add classic" and "Add Volto" options.

Please create a separate issue and provide sufficient implementation detail. I don't understand what this has to do with updating the content on the demo home page.

**Comment by davisagli** [comment]
Done in https://github.com/plone/plone.volto/pull/84
